remove stopped

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -57,7 +57,7 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: Downcase REPO
         run: |
@@ -105,7 +105,6 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
-          platforms: linux/amd64
           cache-from: |
             type=local,src=/tmp/.buildx-cache
             type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
@@ -127,80 +126,80 @@ jobs:
         run: |
           docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
           docker image ls ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
-  deploy:
-    needs: docker-build
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
-    env:
-      REGISTRY: ghcr.io
-      CONTAINER_NAME: lum
+  # deploy:
+  #   needs: docker-build
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   env:
+  #     REGISTRY: ghcr.io
+  #     CONTAINER_NAME: lum
 
-    steps:
-      - name: Downcase REPO
-        run: |
-          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
-      - name: Check secrets
-        run: |
-          if [ -z "${{ secrets.IP }}" ]; then
-            echo "SERVER_IP is missing"
-            exit 1
-          fi
-          if [ -z "${{ secrets.SERVER_USERNAME }}" ]; then
-            echo "SERVER_USERNAME is missing"
-            exit 1
-          fi
-          if [ -z "${{ secrets.SERVER_PASSWORD }}" ]; then
-            echo "SERVER_PASSWORD is missing"
-            exit 1
-          fi
-          echo "All required secrets are present"
-      - name: Deploy to Server
-        uses: appleboy/ssh-action@v1.0.0
-        with:
-          host: ${{ secrets.SERVER_IP }}
-          username: ${{ secrets.SERVER_USERNAME }}
-          password: ${{ secrets.SERVER_PASSWORD }}
-          port: 22
-          debug: true
-          timeout: 30s
-          script: |
-            # Логин в GitHub Container Registry
-            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+  #   steps:
+  #     - name: Downcase REPO
+  #       run: |
+  #         echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
+  #     - name: Check secrets
+  #       run: |
+  #         if [ -z "${{ secrets.IP }}" ]; then
+  #           echo "SERVER_IP is missing"
+  #           exit 1
+  #         fi
+  #         if [ -z "${{ secrets.SERVER_USERNAME }}" ]; then
+  #           echo "SERVER_USERNAME is missing"
+  #           exit 1
+  #         fi
+  #         if [ -z "${{ secrets.SERVER_PASSWORD }}" ]; then
+  #           echo "SERVER_PASSWORD is missing"
+  #           exit 1
+  #         fi
+  #         echo "All required secrets are present"
+  #     - name: Deploy to Server
+  #       uses: appleboy/ssh-action@v1.0.0
+  #       with:
+  #         host: ${{ secrets.SERVER_IP }}
+  #         username: ${{ secrets.SERVER_USERNAME }}
+  #         password: ${{ secrets.SERVER_PASSWORD }}
+  #         port: 22
+  #         debug: true
+  #         timeout: 30s
+  #         script: |
+  #           # Логин в GitHub Container Registry
+  #           echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
-            # Проверка и остановка существующего контейнера
-            if docker ps -a | grep -q "${{ env.CONTAINER_NAME }}"; then
-              echo "Stopping and removing existing container..."
-              docker stop ${{ env.CONTAINER_NAME }}
-              docker rm ${{ env.CONTAINER_NAME }}
-            else
-              echo "No existing container found"
-            fi
+  #           # Проверка и остановка существующего контейнера
+  #           if docker ps -a | grep -q "${{ env.CONTAINER_NAME }}"; then
+  #             echo "Stopping and removing existing container..."
+  #             docker stop ${{ env.CONTAINER_NAME }}
+  #             docker rm ${{ env.CONTAINER_NAME }}
+  #           else
+  #             echo "No existing container found"
+  #           fi
 
-            # Проверка и удаление существующего образа
-            if docker image ls | grep -q "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"; then
-              echo "Removing existing image..."
-              docker image rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
-            else
-              echo "No existing image found"
-            fi
+  #           # Проверка и удаление существующего образа
+  #           if docker image ls | grep -q "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"; then
+  #             echo "Removing existing image..."
+  #             docker image rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
+  #           else
+  #             echo "No existing image found"
+  #           fi
 
-            # Загрузка нового образа
-            echo "Pulling new image..."
-            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
+  #           # Загрузка нового образа
+  #           echo "Pulling new image..."
+  #           docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
 
-            # Запуск нового контейнера
-            echo "Starting new container..."
-            docker run -d \
-              --name ${{ env.CONTAINER_NAME }} \
-              --restart unless-stopped \
-              -e DS_TOKEN=${{ secrets.DS_TOKEN }} \
-              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
+  #           # Запуск нового контейнера
+  #           echo "Starting new container..."
+  #           docker run -d \
+  #             --name ${{ env.CONTAINER_NAME }} \
+  #             --restart unless-stopped \
+  #             -e DS_TOKEN=${{ secrets.DS_TOKEN }} \
+  #             ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
 
-            # Очистка неиспользуемых образов
-            echo "Cleaning up unused images..."
-            docker image prune -f
+  #           # Очистка неиспользуемых образов
+  #           echo "Cleaning up unused images..."
+  #           docker image prune -f
 
-            # Выход из registry
-            docker logout ${{ env.REGISTRY }}
+  #           # Выход из registry
+  #           docker logout ${{ env.REGISTRY }}
